title: Trying out github pages
author: Ben Van Raemdonck
email: Ben-vanraemdonck@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm using this site to try out github pages.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
